2019-04-14 12:56:22,693 ERROR: Exception on /login [GET] [in /home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/routes.py", line 126, in login
    return render_template('login.html', title='Sign in', form=form, authentification_error=False)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/base.html", line 36, in top-level template code
    {% endwith %}{% block content %}{% endblock %}
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/login.html", line 33, in block "content"
    <a href="{{ url_for('reset_password') }}">Click to Reset It</a>
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password'. Did you forget to specify values ['token']?
2019-04-14 12:56:22,697 ERROR: Internal error, please wait until the maintainers fix the issue [in /home/weiss/CODES/BM/intent_gatherer/flask_backend/app/errors.py:13]
2019-04-14 12:56:24,818 ERROR: Exception on /login [GET] [in /home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/routes.py", line 126, in login
    return render_template('login.html', title='Sign in', form=form, authentification_error=False)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/base.html", line 36, in top-level template code
    {% endwith %}{% block content %}{% endblock %}
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/login.html", line 33, in block "content"
    <a href="{{ url_for('reset_password') }}">Click to Reset It</a>
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password'. Did you forget to specify values ['token']?
2019-04-14 12:56:24,822 ERROR: Internal error, please wait until the maintainers fix the issue [in /home/weiss/CODES/BM/intent_gatherer/flask_backend/app/errors.py:13]
2019-04-14 12:57:01,117 ERROR: Exception on /login [GET] [in /home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/routes.py", line 126, in login
    return render_template('login.html', title='Sign in', form=form, authentification_error=False)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/base.html", line 36, in top-level template code
    {% endwith %}{% block content %}{% endblock %}
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/login.html", line 33, in block "content"
    <a href="{{ url_for('reset_password') }}">Click to Reset It</a>
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password'. Did you forget to specify values ['token']?
2019-04-14 12:57:01,119 ERROR: Internal error, please wait until the maintainers fix the issue [in /home/weiss/CODES/BM/intent_gatherer/flask_backend/app/errors.py:13]
2019-04-14 12:57:05,601 INFO: The application started [in /home/weiss/CODES/BM/intent_gatherer/flask_backend/app/__init__.py:44]
2019-04-14 12:57:07,044 ERROR: Exception on /login [GET] [in /home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/routes.py", line 126, in login
    return render_template('login.html', title='Sign in', form=form, authentification_error=False)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/login.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/base.html", line 36, in top-level template code
    {% endwith %}{% block content %}{% endblock %}
  File "/home/weiss/CODES/BM/intent_gatherer/flask_backend/app/templates/login.html", line 33, in block "content"
    <a href="{{ url_for('reset_password') }}">Click to Reset It</a>
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/weiss/CODES/BM/intent_gatherer/intent_gatherer_venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password'. Did you forget to specify values ['token']?
2019-04-14 12:57:07,047 ERROR: Internal error, please wait until the maintainers fix the issue [in /home/weiss/CODES/BM/intent_gatherer/flask_backend/app/errors.py:13]
